[workspace]

members = [
    "mace",
    "makepad",
    "makepad/wasm", 
    "examples/bare_example", 
    "examples/bare_example/wasm",
    "examples/widget_example",
    "examples/widget_example/wasm",
    "examples/editor_example",
    "examples/editor_example/wasm",
    "examples/depricated/webgl_example_wasm",
    "examples/cmdline_example",
    "tools/webserver",
    "tools/brotli_test",
    "builder"
]

[profile.release]
#lto=true
#codegen-units=1
#panic = 'abort'
#opt-level = 'z'
 
